spring:
  application:
    name: funnel
  data:
    redis:
      host: 127.0.0.1
      port: 6379

server:
  port: 8080

scheduler:
  enabled: true

logging:
  level:
    root: INFO

---

spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: 127.0.0.1
      port: 16379

scheduler:
  enabled: false